name: Chroma DB Deployment
on: [push]

jobs:
  process-chroma-db:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
          # Add these to ensure proper authentication
          persist-credentials: true
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}  # If using SSH
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}

      # Rest of your workflow steps...
      - name: Setup directories
        run: |
          mkdir -p Service/vectorDB/vectorDB
          echo "Directory structure:"
          tree -d || true

      - name: Process Chroma Databases
        run: |
          # Create temp workspace
          mkdir -p tmp_unzip

          # Process ZIP files from Service/ directory
          echo "=== Extracting Parts Data ==="
          unzip -o Service/parts_data_vectorDB.zip -d tmp_unzip
          mv "$(find tmp_unzip -type d -name 'parts_data')" Service/vectorDB/vectorDB/

          echo "=== Extracting Service Data ==="
          unzip -o Service/service_data_vectorDB.zip -d tmp_unzip
          mv "$(find tmp_unzip -type d -name 'service_data')" Service/vectorDB/vectorDB/

          # Validate structure
          echo "=== Final Structure ==="
          ls -lR Service/vectorDB/vectorDB
          [ -f Service/vectorDB/vectorDB/parts_data/chroma.sqlite3 ] || exit 1
          [ -f Service/vectorDB/vectorDB/service_data/chroma.sqlite3 ] || exit 1

          # Cleanup
          rm -rf tmp_unzip

      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add Service/vectorDB/vectorDB/
          if ! git diff-index --quiet HEAD --; then
            git commit -m "chore: Update Chroma databases in Service/vectorDB [$(date +%Y-%m-%d)]"
            git push origin HEAD:$GITHUB_REF
          else
            echo "No database changes to commit"
          fi
