name: VectorDB Deployment Pipeline
on: [push]

jobs:
  process-vectordb:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Setup directories
        run: |
          mkdir -p Service/vectorDB/vectorDB
          echo "Directory structure created"
          tree -d || true

      - name: Process and Validate VectorDBs
        run: |
          # Create temporary workspace
          mkdir -p tmp_unzip

          # Process Parts Data
          echo "=== Processing Parts Data ==="
          unzip -o Service/vectorDB/parts_data_vectorDB.zip -d tmp_unzip
          mv tmp_unzip/content/parts_data vectorDB/vectorDB/
          [ -f Service/vectorDB/vectorDB/parts_data/chroma.sqlite3 ] || exit 1

          # Process Service Data
          echo "=== Processing Service Data ==="
          unzip -o Service/vectorDB/service_data_vectorDB.zip -d tmp_unzip
          mv tmp_unzip/content/service_data vectorDB/vectorDB/
          [ -f Service/vectorDB/vectorDB/service_data/chroma.sqlite3 ] || exit 1

          # Cleanup and verify
          rm -rf tmp_unzip
          echo "=== Final Validation ==="
          ls -lR vectorDB/vectorDB/
          [ -f Service/vectorDB/vectorDB/parts_data/chroma.sqlite3 ] && \
          [ -f Service/vectorDB/vectorDB/service_data/chroma.sqlite3 ] || exit 1

      - name: Commit Validated Databases
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git add vectorDB/vectorDB/
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Added validated SQLite vector databases: $(date +%Y-%m-%d)"
            git push origin HEAD:$GITHUB_REF
          else
            echo "No changes to commit"
          fi
